### ISSUE TITLE
No error message when Number is blank and already received/delivered.

### ISSUE THREAD

**Issue by manamirfhk** [rfhk/she-custom#7]
@mra-odoo Hi, Mustufa. It seems that there is no error message when the 'Number' column is blank, or when the PO/SO has been already received/delivered. Could you please check it? Thanks.

**Comment by mra-odoo** [comment]
@manamirfhk Ok we will check and get back to you.

Thanks for reporting.

**Comment by mra-odoo** [comment]
@manamirfhk  Fixed https://github.com/rfhk/she-custom/pull/11/files 
Thanks for reporting.
