### ISSUE TITLE
Does picking_import depend on purchase/sales_order_import?

### ISSUE THREAD

**Issue by manamirfhk** [rfhk/she-custom#9]
@mra-odoo Hi. The picking_import module has Dependencies on the purchase/sales_order_import modules in its Technical Data.
But on first inspection, it seems not to depend.
Could you please tell me what dependencies it has? Sorry for your trouble.

**Comment by mra-odoo** [comment]
@manamirfhk Actually it does not directly depends on sales/purchase import module but only on base log module so we removed dependancy.
https://github.com/rfhk/she-custom/pull/11/files

Thanks,
